### ISSUE TITLE
Add another List - Part #2

### ISSUE THREAD

**Issue by nosvalds** [HazGoddard/hrello#115]
Need to write JS for Clicking the "Add List" button and creating a new list.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/60047271/80870644-b43ff300-8c9f-11ea-86f0-981d1197094d.png">

**Comment by kierancott** [comment]
Part 2 complete, Part 3 remains: Issue https://github.com/HazGoddard/hrello/issues/133
