### ISSUE TITLE
Board JS: Add another list Part 1

### ISSUE THREAD

**Issue by kierancott** [HazGoddard/hrello#62]
Write a script that adds 'add another list' functionality to board components.

**Comment by nosvalds** [comment]
![Screen Shot 2020-05-02 at 4 55 04 PM](https://user-images.githubusercontent.com/60047271/80869000-b4d38c00-8c95-11ea-8bb8-b150e8ae464a.png)
![Screen Shot 2020-05-02 at 4 54 53 PM](https://user-images.githubusercontent.com/60047271/80869001-b56c2280-8c95-11ea-944a-c9f23641eb08.png)

**Comment by nosvalds** [comment]
Added functionality to go back and forth between the two above screen shots. Don't have functionality to create a full new card list yet.
